### ISSUE TITLE
System.Linux.Btrfs.UUID.fromString "" fails

### ISSUE THREAD

**Issue by fuzzy-id** [redneb/hs-btrfs#4]
Hey,

I just stumbled over the following:
```
*Btrbkp> fromString ""
Just (fromString "*** Exception: Prelude.read: no parse
```
where I would expect to get a `Nothing` back. Do you consider fixing things like these in your library?

What do you think of switching to the uuid package? (http://hackage.haskell.org/package/uuid)

**Comment by redneb** [comment]
Thanks for the report. I fixed this bug in version 0.1.2.3 which I already uploaded to hackage.

As for the the `uuid` package, if I remember correctly, I tried initially to use it, but I couldn't get it to work correctly. There was some incompatibly with how `btrfs` (or `btrfs-progs`) handle UUIDs. The `System.Linux.Btrfs.UUID` module on the other hand, is designed to produce identical results to `btrfs-progs`.
